name: Use A11yWatch CI Github action and send results to Sentinel
on:
  workflow_dispatch:
  schedule:
    - cron: "13 12 * * 3"

jobs:
  a11ywatch-ci-action:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        domain:
          - https://digital.canada.ca
          - https://numerique.canada.ca
          - https://encrypted-message.cdssandbox.xyz
          - https://articles.cdssandbox.xyz
          - https://staging.notification.cdssandbox.xyz
          - https://design-system.alpha.canada.ca/en/
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: a11ywatch/github-action@d61a01aad49cc54db0a669cc61b7e85f08994162 # v2.1.10
        with:
          WEBSITE_URL: ${{ matrix.domain }}
          DISABLE_PR_STATS: true
          LIST: false
          SITE_WIDE: true
          SUBDOMAINS: false
          SLIM: true
          TLD: false
      - name: Munge data
        run: |
          a11ywatch -R > out.json
          jq -c '.data[] | del(.cdn_connected, .insight, .user_id)' out.json > output.jsonl
      - name: Forward results to Sentinel
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          file_name: output.jsonl
          log_type: CDS_A11ywatch_Results
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
