name: Use A11yWatch CI Github action and send results to Sentinel
on:
  workflow_dispatch:
  schedule:
    - cron: "13 12 * * 3"

jobs:
  a11ywatch-ci-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:
          - https://digital.canada.ca
          - https://learning-resources.cdssandbox.xyz
          - https://numerique.canada.ca
          - https://secret.cdssandbox.xyz
          - https://articles.cdssandbox.xyz
          - https://staging.notification.cdssandbox.xyz
          - https://forms-staging.cdssandbox.xyz
          - https://design.alpha.canada.ca/en/
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - uses: a11ywatch/github-action@b6c4b69cda04e0abc6a215b37251b737de4f331e # v1.13.0
        with:
          WEBSITE_URL: ${{ matrix.domain }}
          DISABLE_PR_STATS: true
          LIST: false
          SITE_WIDE: true
          SUBDOMAINS: false
          SLIM: true
          TLD: false
      - name: Munge data
        run: |
          a11ywatch -R > out.json
          jq -c '.data[] | del(.cdn_connected, .insight, .user_id)' out.json > output.jsonl
      - name: Forward results to Sentinel
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          file_name: output.jsonl
          log_type: CDS_A11ywatch_Results
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

