name: Use A11YWatch CI Github action and send results to Sentinel
on:
  workflow_dispatch:
  pull_request:
  #schedule:
  #  - cron: "3 5 * * 6"

jobs:
  a11ywatch-ci-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:

          - https://design.alpha.canada.ca/en/
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - uses: a11ywatch/github-action@v1.13.0
        with:
          WEBSITE_URL: ${{ matrix.domain }}
          DISABLE_PR_STATS: true
          LIST: false
          SITE_WIDE: true
          SUBDOMAINS: false
          SLIM: true
          TLD: false
      - name: Sort data
        run: |
          a11ywatch -r > out.json
          echo out.json

      # - name: Munge data
      #  run: |
      #    echo '${{steps.lhci_action.outputs.manifest}}' | jq -c 'map({"url": .url, "domain": "${{ matrix.domain }}", "performance": .summary.performance, "accessibility": .summary.accessibility, "seo": .summary.seo, "pwa": .summary.pwa, "bestPractices": .summary."best-practices"})' | jq -c '.[]' > data.jsonl
      #- name: Forward results to Sentinel
      #  uses: cds-snc/sentinel-forward-data-action@main
      #  with:
      #    file_name: data.jsonl
      #    log_type: CDS_Lighthouse_Results
      #    log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      #    log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

