name: Use Lighthouse CI Github action and send results to Sentinel
on:
  workflow_dispatch:
  schedule:
    - cron: "15 12 * * 0"
  pull_request:

jobs:
  lighthouse-ci-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain:
          - https://secret.cdssandbox.xyz
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: Install spider and run on domain
        id: spider
        run: |
          sudo GOBIN=/usr/local/bin/ GO111MODULE=on go install github.com/jaeles-project/gospider@latest
          echo "urls=$(gospider -s '"${{ matrix.domain }}"' --quiet -c 10 -d 4 --json --no-redirect | grep '"type":"url"' | jq -r '.output' | sed 's//*$//' | sort -u)" >> $GITHUB_OUTPUT
      - name: Test output
        run: cat '${{ steps.spider.outputs.urls }}'


