name: Runs OWASP ZAP full scans
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  pull_request:

jobs:
  oswasp-zap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain:
          - https://www.example.com
          # - https://digital.canada.ca
          # - https://numerique.canada.ca
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - name: OSWASP ZAP - Vulnerability Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          allow_issue_writing: false
          cmd_options: '-s'
          target: ${{ matrix.domain }}
          rules_file_name: "oswasp_zap_rules.tsv"
      - name: Extract alerts
        run: |
          jq '.site[] as $site | .site[] | .alerts[] | .host = $site."@host" | .' report_json.json > output.jsonl
          cat output.jsonl
      #- name: Forward results to Sentinel
      #  uses: cds-snc/sentinel-forward-data-action@main
      #  with:
      #    file_name: nuclei.log
      #    log_type: CDS_Nuclei_Results
      #    log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      #    log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
