name: Runs OWASP ZAP full scans
on:
  workflow_dispatch:
  schedule:
    - cron: "23 16 * * 0"

env:
  CONTACT_FORMS: support|contactus|contact|careers|carrieres|contact-us|contact-us-fr|contactez

jobs:
  owasp-zap:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        domain:
          - https://learning-resources.cdssandbox.xyz
          - https://secret.cdssandbox.xyz
          - https://url-shortener.cdssandbox.xyz/
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: OWASP ZAP - Vulnerability Scan
        uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98 # v0.4.0
        with:
          allow_issue_writing: false
          cmd_options: '-s -z "-config globalexcludeurl.url_list.url.regex=^.*/(${{ env.CONTACT_FORMS }})/?$"'
          target: ${{ matrix.domain }}
          rules_file_name: "owasp_zap_rules.tsv"
      - name: Extract alerts
        run: |
          jq -c '.site[] as $site | .site[] | .alerts[] | .host = $site."@host" | .' report_json.json > output.jsonl
          sort -u output.jsonl > unique_output.jsonl
      - name: Forward results to Sentinel
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          file_name: unique_output.jsonl
          log_type: CDS_OWASPZap_Results
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
